window.DAD_JOKES = [
  "I'm afraid for the calendar. Its days are numbered.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "What do you call fake spaghetti? An impasta.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "How do you organize a space party? You planet.",
  "Why was the math book sad? It had too many problems.",
  "Why can't your nose be 12 inches long? Because then it would be a foot.",
  "What did the ocean say to the beach? Nothing. It just waved.",
  "Why did the coffee call the police? It got mugged.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "What do you call a fish wearing a bow tie? Sofishticated.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a sleeping bull? A bulldozer.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the stadium get hot after the game? All the fans left.",
  "What do you call a can opener that doesn't work? A can't opener.",
  "Why did the computer go to the doctor? It had a virus.",
  "What do you call a boomerang that doesn't come back? A stick.",
  "Why did the picture go to jail? It was framed.",
  "What do you call a cow with no legs? Ground beef.",
  "What do you call a cow with two legs? Lean beef.",
  "What do you call a cow that plays music? A moo-sician.",
  "What do you call a magical dog? A labracadabrador.",
  "What do you call an alligator in a vest? An investigator.",
  "What do you call a dinosaur with a huge vocabulary? A thesaurus.",
  "What do you call a pile of cats? A meowtain.",
  "What do you call a pony with a sore throat? A little horse.",
  "What do you call a snowman in summer? A puddle.",
  "What do you call a pig that knows karate? A pork chop.",
  "Why did the tomato blush? It saw the salad dressing.",
  "Why did the banana visit the doctor? It wasn't peeling well.",
  "Why did the orange stop rolling? It ran out of juice.",
  "What do you call a sad strawberry? A blueberry.",
  "Why did the cookie go to the hospital? It felt crumby.",
  "Why was the mushroom invited to every party? Because he was a fungi.",
  "Why did the bread ask for some space? It kneaded room to rise.",
  "Why did the melon jump into the lake? It wanted to be a watermelon.",
  "Why don't oysters share their snacks? They're shellfish.",
  "What did the grape say when it got stepped on? Nothing. It just let out a little wine.",
  "Why did the cheese go to the gym? It wanted to get shredded.",
  "Why did the ice cream truck break down? It hit a rocky road.",
  "Why did the soda go to school? It wanted to ace the pop quiz.",
  "Why did the peanut go to the party? It was nuts about everyone there.",
  "Why did the tortilla chip start dancing? The salsa came on.",
  "Why did the taco cross the road? To get to the shell station.",
  "Why did the chicken join the band? It already had drumsticks.",
  "Why did the cow cross the road? To get to the udder side.",
  "Why did the duck get a parking ticket? It parked in a no-quacking zone.",
  "Why did the frog take the bus? His car got toad.",
  "Why do fish live in salt water? Because pepper makes them sneeze.",
  "What do you call a fish with no eyes? Fsh.",
  "Why doesn't the crab share? It's a little shellfish.",
  "Why is an octopus great at multitasking? It always has a hand to spare.",
  "Why did the whale bring a suitcase? It was going on a krill-cation.",
  "Why did the owl invite everyone over? It wanted to have a hoot.",
  "Why did the bee get married? It found its honey.",
  "Why did the ant bring a suitcase? It had big ant-icipations.",
  "Why did the snail paint an S on its car? So people would say, \"Look at that S-car-go!\"",
  "Why did the penguin bring a suitcase? It was going on an ice trip.",
  "Why did the polar bear get the job? It was cool under pressure.",
  "Why does a flamingo stand on one leg? Because if it lifted both, it would fall over.",
  "Why did the elephant bring a suitcase? It had plenty of trunk space.",
  "Why don't leopards play hide-and-seek? They're always spotted.",
  "What do you call a sleeping dinosaur? A dino-snore.",
  "Why was the cat sitting on the computer? It wanted to keep an eye on the mouse.",
  "Why did the dog sit in the shade? It didn't want to be a hot dog.",
  "Why did the horse get promoted? It was a stable employee.",
  "Why did the sheep take a vacation? It needed some ewe time.",
  "Why did the goat start a business? It wanted to be the G.O.A.T.",
  "Why did the spider buy a computer? It wanted to improve its web design.",
  "Why did the pencil get promoted? It always had sharp ideas.",
  "Why did the eraser feel confident? It had a clean slate.",
  "Why did the ruler get invited to the meeting? It always measured up.",
  "Why did the notebook go to the gym? It wanted a stronger binding.",
  "Why was the backpack exhausted? It had too much baggage.",
  "Why did the clock get in trouble? It kept tocking in class.",
  "Why was the broom late? It overswept.",
  "Why did the mop get a compliment? It cleaned up nicely.",
  "Why did the window ask for a raise? It wanted a pane increase.",
  "Why did the chair get promoted? It always supported everyone.",
  "Why did the couch take a vacation? It needed time to recline.",
  "Why was the lamp proud? It had a bright idea.",
  "Why did the refrigerator become a detective? It knew how to keep things cool.",
  "Why did the washing machine start a band? It had a great spin on everything.",
  "Why did the dryer become a comedian? It had very dry humor.",
  "Why did the toilet paper roll down the hill? To get to the bottom.",
  "Why did the soap win an award? It gave a clean performance.",
  "I used to hate facial hair, but then it grew on me.",
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "I ordered a chicken and an egg online. I'll let you know.",
  "Want to hear a joke about paper? Never mind. It's tearable.",
  "I don't trust stairs. They're always up to something.",
  "I told my suitcase there would be no vacation this year. Now I'm dealing with emotional baggage.",
  "I tried to catch some fog yesterday. Mist.",
  "I wondered why the baseball kept getting bigger. Then it hit me.",
  "I have a joke about construction, but I'm still working on it.",
  "Why did the calendar take a break? Its days were numbered.",
  "I asked the calendar how things were going. Its days were numbered.",
  "The calendar showed up with an excuse. Its days were numbered.",
  "Dad checked in on the calendar. Its days were numbered.",
  "Why did the bicycle take a break? It was two-tired.",
  "I asked the bicycle how things were going. It was two-tired.",
  "The bicycle showed up with an excuse. It was two-tired.",
  "Dad checked in on the bicycle. It was two-tired.",
  "Why did the elevator take a break? It needed a lift.",
  "I asked the elevator how things were going. It needed a lift.",
  "The elevator showed up with an excuse. It needed a lift.",
  "Dad checked in on the elevator. It needed a lift.",
  "Why did the scarecrow take a break? It was outstanding in its field.",
  "I asked the scarecrow how things were going. It was outstanding in its field.",
  "The scarecrow showed up with an excuse. It was outstanding in its field.",
  "Dad checked in on the scarecrow. It was outstanding in its field.",
  "Why did the math book take a break? It had too many problems.",
  "I asked the math book how things were going. It had too many problems.",
  "The math book showed up with an excuse. It had too many problems.",
  "Dad checked in on the math book. It had too many problems.",
  "Why did the vacuum take a break? The whole thing sucked.",
  "I asked the vacuum how things were going. The whole thing sucked.",
  "The vacuum showed up with an excuse. The whole thing sucked.",
  "Dad checked in on the vacuum. The whole thing sucked.",
  "Why did the coffee cup take a break? It got mugged.",
  "I asked the coffee cup how things were going. It got mugged.",
  "The coffee cup showed up with an excuse. It got mugged.",
  "Dad checked in on the coffee cup. It got mugged.",
  "Why did the ocean take a break? It just waved.",
  "I asked the ocean how things were going. It just waved.",
  "The ocean showed up with an excuse. It just waved.",
  "Dad checked in on the ocean. It just waved.",
  "Why did the atom take a break? It made up everything.",
  "I asked the atom how things were going. It made up everything.",
  "The atom showed up with an excuse. It made up everything.",
  "Dad checked in on the atom. It made up everything.",
  "Why did the anti-gravity book take a break? It was impossible to put down.",
  "I asked the anti-gravity book how things were going. It was impossible to put down.",
  "The anti-gravity book showed up with an excuse. It was impossible to put down.",
  "Dad checked in on the anti-gravity book. It was impossible to put down.",
  "Why did the paper joke take a break? It was tearable.",
  "I asked the paper joke how things were going. It was tearable.",
  "The paper joke showed up with an excuse. It was tearable.",
  "Dad checked in on the paper joke. It was tearable.",
  "Why did the cheese wheel take a break? It wanted to feel grate.",
  "I asked the cheese wheel how things were going. It wanted to feel grate.",
  "The cheese wheel showed up with an excuse. It wanted to feel grate.",
  "Dad checked in on the cheese wheel. It wanted to feel grate.",
  "Why did the fish in a bow tie take a break? It was feeling sofishticated.",
  "I asked the fish in a bow tie how things were going. It was feeling sofishticated.",
  "The fish in a bow tie showed up with an excuse. It was feeling sofishticated.",
  "Dad checked in on the fish in a bow tie. It was feeling sofishticated.",
  "Why did the egg take a break? It kept cracking up.",
  "I asked the egg how things were going. It kept cracking up.",
  "The egg showed up with an excuse. It kept cracking up.",
  "Dad checked in on the egg. It kept cracking up.",
  "Why did the pizza take a break? It wanted a slice of the action.",
  "I asked the pizza how things were going. It wanted a slice of the action.",
  "The pizza showed up with an excuse. It wanted a slice of the action.",
  "Dad checked in on the pizza. It wanted a slice of the action.",
  "Why did the orange take a break? It found the idea a-peeling.",
  "I asked the orange how things were going. It found the idea a-peeling.",
  "The orange showed up with an excuse. It found the idea a-peeling.",
  "Dad checked in on the orange. It found the idea a-peeling.",
  "Why did the banana take a break? It had to split.",
  "I asked the banana how things were going. It had to split.",
  "The banana showed up with an excuse. It had to split.",
  "Dad checked in on the banana. It had to split.",
  "Why did the grape take a break? It was in a jam.",
  "I asked the grape how things were going. It was in a jam.",
  "The grape showed up with an excuse. It was in a jam.",
  "Dad checked in on the grape. It was in a jam.",
  "Why did the bread loaf take a break? It kneaded some dough.",
  "I asked the bread loaf how things were going. It kneaded some dough.",
  "The bread loaf showed up with an excuse. It kneaded some dough.",
  "Dad checked in on the bread loaf. It kneaded some dough.",
  "Why did the donut take a break? It felt a little empty in the middle.",
  "I asked the donut how things were going. It felt a little empty in the middle.",
  "The donut showed up with an excuse. It felt a little empty in the middle.",
  "Dad checked in on the donut. It felt a little empty in the middle.",
  "Why did the cookie take a break? It was feeling crumby.",
  "I asked the cookie how things were going. It was feeling crumby.",
  "The cookie showed up with an excuse. It was feeling crumby.",
  "Dad checked in on the cookie. It was feeling crumby.",
  "Why did the potato take a break? It had its eyes on the prize.",
  "I asked the potato how things were going. It had its eyes on the prize.",
  "The potato showed up with an excuse. It had its eyes on the prize.",
  "Dad checked in on the potato. It had its eyes on the prize.",
  "Why did the corn cob take a break? It had an ear for good ideas.",
  "I asked the corn cob how things were going. It had an ear for good ideas.",
  "The corn cob showed up with an excuse. It had an ear for good ideas.",
  "Dad checked in on the corn cob. It had an ear for good ideas.",
  "Why did the mushroom take a break? It was a fungi to be around.",
  "I asked the mushroom how things were going. It was a fungi to be around.",
  "The mushroom showed up with an excuse. It was a fungi to be around.",
  "Dad checked in on the mushroom. It was a fungi to be around.",
  "Why did the lettuce head take a break? It wanted to turnip the beet.",
  "I asked the lettuce head how things were going. It wanted to turnip the beet.",
  "The lettuce head showed up with an excuse. It wanted to turnip the beet.",
  "Dad checked in on the lettuce head. It wanted to turnip the beet.",
  "Why did the tomato take a break? It needed time to ketchup.",
  "I asked the tomato how things were going. It needed time to ketchup.",
  "The tomato showed up with an excuse. It needed time to ketchup.",
  "Dad checked in on the tomato. It needed time to ketchup.",
  "Why did the mustard bottle take a break? It couldn't cut the mustard.",
  "I asked the mustard bottle how things were going. It couldn't cut the mustard.",
  "The mustard bottle showed up with an excuse. It couldn't cut the mustard.",
  "Dad checked in on the mustard bottle. It couldn't cut the mustard.",
  "Why did the pickle take a break? It was kind of a big dill.",
  "I asked the pickle how things were going. It was kind of a big dill.",
  "The pickle showed up with an excuse. It was kind of a big dill.",
  "Dad checked in on the pickle. It was kind of a big dill.",
  "Why did the peanut take a break? It was nuts about the idea.",
  "I asked the peanut how things were going. It was nuts about the idea.",
  "The peanut showed up with an excuse. It was nuts about the idea.",
  "Dad checked in on the peanut. It was nuts about the idea.",
  "Why did the waffle take a break? It couldn't make up its mind.",
  "I asked the waffle how things were going. It couldn't make up its mind.",
  "The waffle showed up with an excuse. It couldn't make up its mind.",
  "Dad checked in on the waffle. It couldn't make up its mind.",
  "Why did the pancake take a break? It flipped over the idea.",
  "I asked the pancake how things were going. It flipped over the idea.",
  "The pancake showed up with an excuse. It flipped over the idea.",
  "Dad checked in on the pancake. It flipped over the idea.",
  "Why did the cereal box take a break? It was ready to bowl everyone over.",
  "I asked the cereal box how things were going. It was ready to bowl everyone over.",
  "The cereal box showed up with an excuse. It was ready to bowl everyone over.",
  "Dad checked in on the cereal box. It was ready to bowl everyone over.",
  "Why did the milk carton take a break? It had a dairy important meeting.",
  "I asked the milk carton how things were going. It had a dairy important meeting.",
  "The milk carton showed up with an excuse. It had a dairy important meeting.",
  "Dad checked in on the milk carton. It had a dairy important meeting.",
  "Why did the ice cream cone take a break? It needed to chill.",
  "I asked the ice cream cone how things were going. It needed to chill.",
  "The ice cream cone showed up with an excuse. It needed to chill.",
  "Dad checked in on the ice cream cone. It needed to chill.",
  "Why did the popcorn kernel take a break? It was popping with ideas.",
  "I asked the popcorn kernel how things were going. It was popping with ideas.",
  "The popcorn kernel showed up with an excuse. It was popping with ideas.",
  "Dad checked in on the popcorn kernel. It was popping with ideas.",
  "Why did the soda can take a break? It felt pressured.",
  "I asked the soda can how things were going. It felt pressured.",
  "The soda can showed up with an excuse. It felt pressured.",
  "Dad checked in on the soda can. It felt pressured.",
  "Why did the tea bag take a break? It needed to steep on it.",
  "I asked the tea bag how things were going. It needed to steep on it.",
  "The tea bag showed up with an excuse. It needed to steep on it.",
  "Dad checked in on the tea bag. It needed to steep on it.",
  "Why did the lemon take a break? It was feeling a little sour.",
  "I asked the lemon how things were going. It was feeling a little sour.",
  "The lemon showed up with an excuse. It was feeling a little sour.",
  "Dad checked in on the lemon. It was feeling a little sour.",
  "Why did the lime take a break? It needed some zest.",
  "I asked the lime how things were going. It needed some zest.",
  "The lime showed up with an excuse. It needed some zest.",
  "Dad checked in on the lime. It needed some zest.",
  "Why did the avocado take a break? It wanted to guac and roll.",
  "I asked the avocado how things were going. It wanted to guac and roll.",
  "The avocado showed up with an excuse. It wanted to guac and roll.",
  "Dad checked in on the avocado. It wanted to guac and roll.",
  "Why did the taco take a break? It had a lot to taco 'bout.",
  "I asked the taco how things were going. It had a lot to taco 'bout.",
  "The taco showed up with an excuse. It had a lot to taco 'bout.",
  "Dad checked in on the taco. It had a lot to taco 'bout.",
  "Why did the burrito take a break? It was all wrapped up.",
  "I asked the burrito how things were going. It was all wrapped up.",
  "The burrito showed up with an excuse. It was all wrapped up.",
  "Dad checked in on the burrito. It was all wrapped up.",
  "Why did the sandwich take a break? It was stuck in the middle.",
  "I asked the sandwich how things were going. It was stuck in the middle.",
  "The sandwich showed up with an excuse. It was stuck in the middle.",
  "Dad checked in on the sandwich. It was stuck in the middle.",
  "Why did the burger take a break? It had beef with the schedule.",
  "I asked the burger how things were going. It had beef with the schedule.",
  "The burger showed up with an excuse. It had beef with the schedule.",
  "Dad checked in on the burger. It had beef with the schedule.",
  "Why did the French fry take a break? It was feeling salty.",
  "I asked the French fry how things were going. It was feeling salty.",
  "The French fry showed up with an excuse. It was feeling salty.",
  "Dad checked in on the French fry. It was feeling salty.",
  "Why did the hot dog take a break? It was on a roll.",
  "I asked the hot dog how things were going. It was on a roll.",
  "The hot dog showed up with an excuse. It was on a roll.",
  "Dad checked in on the hot dog. It was on a roll.",
  "Why did the ketchup bottle take a break? It was trying to catch up.",
  "I asked the ketchup bottle how things were going. It was trying to catch up.",
  "The ketchup bottle showed up with an excuse. It was trying to catch up.",
  "Dad checked in on the ketchup bottle. It was trying to catch up.",
  "Why did the onion take a break? It had layers of feelings.",
  "I asked the onion how things were going. It had layers of feelings.",
  "The onion showed up with an excuse. It had layers of feelings.",
  "Dad checked in on the onion. It had layers of feelings.",
  "Why did the garlic clove take a break? It needed to spice things up.",
  "I asked the garlic clove how things were going. It needed to spice things up.",
  "The garlic clove showed up with an excuse. It needed to spice things up.",
  "Dad checked in on the garlic clove. It needed to spice things up.",
  "Why did the apple take a break? It was the core of the problem.",
  "I asked the apple how things were going. It was the core of the problem.",
  "The apple showed up with an excuse. It was the core of the problem.",
  "Dad checked in on the apple. It was the core of the problem.",
  "Why did the bean take a break? It had bean there before.",
  "I asked the bean how things were going. It had bean there before.",
  "The bean showed up with an excuse. It had bean there before.",
  "Dad checked in on the bean. It had bean there before.",
  "Why did the carrot take a break? It couldn't see the point.",
  "I asked the carrot how things were going. It couldn't see the point.",
  "The carrot showed up with an excuse. It couldn't see the point.",
  "Dad checked in on the carrot. It couldn't see the point.",
  "Why did the broccoli stalk take a break? It was branching out.",
  "I asked the broccoli stalk how things were going. It was branching out.",
  "The broccoli stalk showed up with an excuse. It was branching out.",
  "Dad checked in on the broccoli stalk. It was branching out.",
  "Why did the celery stalk take a break? It was stalking around.",
  "I asked the celery stalk how things were going. It was stalking around.",
  "The celery stalk showed up with an excuse. It was stalking around.",
  "Dad checked in on the celery stalk. It was stalking around.",
  "Why did the cabbage take a break? It was a head of the rest.",
  "I asked the cabbage how things were going. It was a head of the rest.",
  "The cabbage showed up with an excuse. It was a head of the rest.",
  "Dad checked in on the cabbage. It was a head of the rest.",
  "Why did the pea pod take a break? It wanted a little peas and quiet.",
  "I asked the pea pod how things were going. It wanted a little peas and quiet.",
  "The pea pod showed up with an excuse. It wanted a little peas and quiet.",
  "Dad checked in on the pea pod. It wanted a little peas and quiet.",
  "Why did the beet take a break? It couldn't miss a beat.",
  "I asked the beet how things were going. It couldn't miss a beat.",
  "The beet showed up with an excuse. It couldn't miss a beat.",
  "Dad checked in on the beet. It couldn't miss a beat.",
  "Why did the radish take a break? It was feeling rad-ish.",
  "I asked the radish how things were going. It was feeling rad-ish.",
  "The radish showed up with an excuse. It was feeling rad-ish.",
  "Dad checked in on the radish. It was feeling rad-ish.",
  "Why did the turnip take a break? It wanted to turn up.",
  "I asked the turnip how things were going. It wanted to turn up.",
  "The turnip showed up with an excuse. It wanted to turn up.",
  "Dad checked in on the turnip. It wanted to turn up.",
  "Why did the shrimp take a break? It felt a little shellfish.",
  "I asked the shrimp how things were going. It felt a little shellfish.",
  "The shrimp showed up with an excuse. It felt a little shellfish.",
  "Dad checked in on the shrimp. It felt a little shellfish.",
  "Why did the crab take a break? It was feeling crabby.",
  "I asked the crab how things were going. It was feeling crabby.",
  "The crab showed up with an excuse. It was feeling crabby.",
  "Dad checked in on the crab. It was feeling crabby.",
  "Why did the lobster take a break? It was clawing its way up.",
  "I asked the lobster how things were going. It was clawing its way up.",
  "The lobster showed up with an excuse. It was clawing its way up.",
  "Dad checked in on the lobster. It was clawing its way up.",
  "Why did the clam take a break? It kept everything bottled up in its shell.",
  "I asked the clam how things were going. It kept everything bottled up in its shell.",
  "The clam showed up with an excuse. It kept everything bottled up in its shell.",
  "Dad checked in on the clam. It kept everything bottled up in its shell.",
  "Why did the oyster take a break? The world was its oyster.",
  "I asked the oyster how things were going. The world was its oyster.",
  "The oyster showed up with an excuse. The world was its oyster.",
  "Dad checked in on the oyster. The world was its oyster.",
  "Why did the salmon take a break? It was swimming upstream.",
  "I asked the salmon how things were going. It was swimming upstream.",
  "The salmon showed up with an excuse. It was swimming upstream.",
  "Dad checked in on the salmon. It was swimming upstream.",
  "Why did the tuna take a break? It needed to tune up.",
  "I asked the tuna how things were going. It needed to tune up.",
  "The tuna showed up with an excuse. It needed to tune up.",
  "Dad checked in on the tuna. It needed to tune up.",
  "Why did the owl take a break? It was having a hoot.",
  "I asked the owl how things were going. It was having a hoot.",
  "The owl showed up with an excuse. It was having a hoot.",
  "Dad checked in on the owl. It was having a hoot.",
  "Why did the cow take a break? It was in a moo-d.",
  "I asked the cow how things were going. It was in a moo-d.",
  "The cow showed up with an excuse. It was in a moo-d.",
  "Dad checked in on the cow. It was in a moo-d.",
  "Why did the horse take a break? It was horsing around.",
  "I asked the horse how things were going. It was horsing around.",
  "The horse showed up with an excuse. It was horsing around.",
  "Dad checked in on the horse. It was horsing around.",
  "Why did the chicken take a break? It was too chicken to try.",
  "I asked the chicken how things were going. It was too chicken to try.",
  "The chicken showed up with an excuse. It was too chicken to try.",
  "Dad checked in on the chicken. It was too chicken to try.",
  "Why did the duck take a break? It had a quacking good plan.",
  "I asked the duck how things were going. It had a quacking good plan.",
  "The duck showed up with an excuse. It had a quacking good plan.",
  "Dad checked in on the duck. It had a quacking good plan.",
  "Why did the goat take a break? It wanted to be the G.O.A.T.",
  "I asked the goat how things were going. It wanted to be the G.O.A.T.",
  "The goat showed up with an excuse. It wanted to be the G.O.A.T.",
  "Dad checked in on the goat. It wanted to be the G.O.A.T.",
  "Why did the sheep take a break? It was feeling baa-d.",
  "I asked the sheep how things were going. It was feeling baa-d.",
  "The sheep showed up with an excuse. It was feeling baa-d.",
  "Dad checked in on the sheep. It was feeling baa-d.",
  "Why did the pig take a break? It was hogging the spotlight.",
  "I asked the pig how things were going. It was hogging the spotlight.",
  "The pig showed up with an excuse. It was hogging the spotlight.",
  "Dad checked in on the pig. It was hogging the spotlight.",
  "Why did the dog take a break? It had a ruff day.",
  "I asked the dog how things were going. It had a ruff day.",
  "The dog showed up with an excuse. It had a ruff day.",
  "Dad checked in on the dog. It had a ruff day.",
  "Why did the cat take a break? It was feline fine.",
  "I asked the cat how things were going. It was feline fine.",
  "The cat showed up with an excuse. It was feline fine.",
  "Dad checked in on the cat. It was feline fine.",
  "Why did the mouse take a break? It clicked with the idea.",
  "I asked the mouse how things were going. It clicked with the idea.",
  "The mouse showed up with an excuse. It clicked with the idea.",
  "Dad checked in on the mouse. It clicked with the idea.",
  "Why did the bee take a break? It was buzzing with excitement.",
  "I asked the bee how things were going. It was buzzing with excitement.",
  "The bee showed up with an excuse. It was buzzing with excitement.",
  "Dad checked in on the bee. It was buzzing with excitement.",
  "Why did the ant take a break? It had tiny plans but big ant-itions.",
  "I asked the ant how things were going. It had tiny plans but big ant-itions.",
  "The ant showed up with an excuse. It had tiny plans but big ant-itions.",
  "Dad checked in on the ant. It had tiny plans but big ant-itions.",
  "Why did the butterfly take a break? It needed to wing it.",
  "I asked the butterfly how things were going. It needed to wing it.",
  "The butterfly showed up with an excuse. It needed to wing it.",
  "Dad checked in on the butterfly. It needed to wing it.",
  "Why did the snail take a break? It wanted to take things slow.",
  "I asked the snail how things were going. It wanted to take things slow.",
  "The snail showed up with an excuse. It wanted to take things slow.",
  "Dad checked in on the snail. It wanted to take things slow.",
  "Why did the turtle take a break? It needed to come out of its shell.",
  "I asked the turtle how things were going. It needed to come out of its shell.",
  "The turtle showed up with an excuse. It needed to come out of its shell.",
  "Dad checked in on the turtle. It needed to come out of its shell.",
  "Why did the frog take a break? It wanted to jump to conclusions.",
  "I asked the frog how things were going. It wanted to jump to conclusions.",
  "The frog showed up with an excuse. It wanted to jump to conclusions.",
  "Dad checked in on the frog. It wanted to jump to conclusions.",
  "Why did the kangaroo take a break? It had a hopping schedule.",
  "I asked the kangaroo how things were going. It had a hopping schedule.",
  "The kangaroo showed up with an excuse. It had a hopping schedule.",
  "Dad checked in on the kangaroo. It had a hopping schedule.",
  "Why did the penguin take a break? It needed to break the ice.",
  "I asked the penguin how things were going. It needed to break the ice.",
  "The penguin showed up with an excuse. It needed to break the ice.",
  "Dad checked in on the penguin. It needed to break the ice.",
  "Why did the polar bear take a break? It was cool under pressure.",
  "I asked the polar bear how things were going. It was cool under pressure.",
  "The polar bear showed up with an excuse. It was cool under pressure.",
  "Dad checked in on the polar bear. It was cool under pressure.",
  "Why did the seal take a break? It gave the idea its seal of approval.",
  "I asked the seal how things were going. It gave the idea its seal of approval.",
  "The seal showed up with an excuse. It gave the idea its seal of approval.",
  "Dad checked in on the seal. It gave the idea its seal of approval.",
  "Why did the octopus take a break? It had its hands full.",
  "I asked the octopus how things were going. It had its hands full.",
  "The octopus showed up with an excuse. It had its hands full.",
  "Dad checked in on the octopus. It had its hands full.",
  "Why did the squid take a break? It was ink-redibly busy.",
  "I asked the squid how things were going. It was ink-redibly busy.",
  "The squid showed up with an excuse. It was ink-redibly busy.",
  "Dad checked in on the squid. It was ink-redibly busy.",
  "Why did the shark take a break? It wanted to take a bite out of the problem.",
  "I asked the shark how things were going. It wanted to take a bite out of the problem.",
  "The shark showed up with an excuse. It wanted to take a bite out of the problem.",
  "Dad checked in on the shark. It wanted to take a bite out of the problem.",
  "Why did the whale take a break? It was having a whale of a time.",
  "I asked the whale how things were going. It was having a whale of a time.",
  "The whale showed up with an excuse. It was having a whale of a time.",
  "Dad checked in on the whale. It was having a whale of a time.",
  "Why did the dolphin take a break? It clicked with everyone.",
  "I asked the dolphin how things were going. It clicked with everyone.",
  "The dolphin showed up with an excuse. It clicked with everyone.",
  "Dad checked in on the dolphin. It clicked with everyone.",
  "Why did the flamingo take a break? It was standing out.",
  "I asked the flamingo how things were going. It was standing out.",
  "The flamingo showed up with an excuse. It was standing out.",
  "Dad checked in on the flamingo. It was standing out.",
  "Why did the hedgehog take a break? It had a point.",
  "I asked the hedgehog how things were going. It had a point.",
  "The hedgehog showed up with an excuse. It had a point.",
  "Dad checked in on the hedgehog. It had a point.",
  "Why did the porcupine take a break? It was a little prickly.",
  "I asked the porcupine how things were going. It was a little prickly.",
  "The porcupine showed up with an excuse. It was a little prickly.",
  "Dad checked in on the porcupine. It was a little prickly.",
  "Why did the rabbit take a break? It was all ears.",
  "I asked the rabbit how things were going. It was all ears.",
  "The rabbit showed up with an excuse. It was all ears.",
  "Dad checked in on the rabbit. It was all ears.",
  "Why did the deer take a break? It was a dear friend.",
  "I asked the deer how things were going. It was a dear friend.",
  "The deer showed up with an excuse. It was a dear friend.",
  "Dad checked in on the deer. It was a dear friend.",
  "Why did the bear take a break? It could barely keep up.",
  "I asked the bear how things were going. It could barely keep up.",
  "The bear showed up with an excuse. It could barely keep up.",
  "Dad checked in on the bear. It could barely keep up.",
  "Why did the lion take a break? It wasn't lion about it.",
  "I asked the lion how things were going. It wasn't lion about it.",
  "The lion showed up with an excuse. It wasn't lion about it.",
  "Dad checked in on the lion. It wasn't lion about it.",
  "Why did the tiger take a break? It earned its stripes.",
  "I asked the tiger how things were going. It earned its stripes.",
  "The tiger showed up with an excuse. It earned its stripes.",
  "Dad checked in on the tiger. It earned its stripes."
];
