window.SCHOOL_SAFE_JOKES = [
  "I asked the librarian if the library had books on paranoia. She whispered, “They’re right behind you.”",
  "My math book looks sad. It has too many problems.",
  "I tried to catch some fog yesterday. Mist.",
  "The shovel was a groundbreaking invention.",
  "I’m reading a book about anti-gravity. It’s impossible to put down.",
  "I used to hate facial hair, but then it grew on me.",
  "What do you call a sleeping bull? A bulldozer.",
  "What do you call a bear with no teeth? A gummy bear.",
  "What did one wall say to the other wall? I’ll meet you at the corner.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "What kind of music do balloons hate? Pop music.",
  "What did the ocean say to the beach? Nothing. It just waved.",
  "What did the zero say to the eight? Nice belt.",
  "Why was the broom late? It swept in.",
  "Why don’t eggs tell jokes? They might crack each other up.",
  "What do clouds wear under their shorts? Thunderwear.",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you call a fish wearing a bow tie? Sofishticated.",
  "How does a penguin build a house? Igloos it together.",
  "What do you call a dinosaur with a huge vocabulary? A thesaurus.",
  "Why was the calendar nervous? Its days were numbered.",
  "Why are elevator jokes so good? They work on many levels.",
  "What did the grape do when it got stepped on? Nothing. It just let out a little wine.",
  "What do you call a fake noodle? An impasta.",
  "Why did the cookie go to the doctor? It felt crummy.",
  "Why did the computer go to the doctor? It caught a virus.",
  "Why did the student eat the homework? The teacher said it was a piece of cake.",
  "What did the pencil say to the paper? Write on.",
  "Why was the music teacher good at baseball? Great pitch.",
  "Why did the tomato blush? It saw the salad dressing.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "What did one plate say to the other? Dinner’s on me.",
  "What kind of key opens a banana? A monkey.",
  "What do you call a can opener that doesn’t work? A can’t opener.",
  "Why did the golfer bring two pairs of pants? In case of a hole in one.",
  "What do you call a boomerang that won’t come back? A stick.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "What do you call a cow with no legs? Ground beef.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why do seagulls fly over the sea? If they flew over the bay, they’d be bagels.",
  "What do you call a snowman in summer? A puddle.",
  "Why did the banana go to the doctor? It wasn’t peeling well.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the picture go to jail? It was framed.",
  "What do you call a very careful wolf? Aware-wolf.",
  "Why did the teddy bear skip dessert? It was stuffed.",
  "Why did the orange stop rolling? It ran out of juice.",
  "What do you call a pile of cats? A meowtain.",
  "Why can’t you trust stairs? They’re always up to something.",
  "What did the left eye say to the right eye? Between us, something smells.",
  "What kind of tree fits in your hand? A palm tree.",
  "What do you call a duck that gets straight A’s? A wise quacker.",
  "Why did the book join the police? It wanted to go undercover.",
  "Why did the clock get sent to the principal? It kept tocking back.",
  "What do you call a snail on a ship? A snailor.",
  "Why did the melon jump into the lake? It wanted to be a watermelon.",
  "What do you call a cow that plays music? A moo-sician.",
  "What does a lemon say when it answers the phone? Yellow?",
  "Why was six afraid of seven? Because seven ate nine.",
  "What did one hat say to the other? You stay here. I’ll go on ahead.",
  "Why do fish live in salt water? Because pepper makes them sneeze.",
  "What do you call a dog magician? A labracadabrador.",
  "Why did the coffee call the police? It got mugged.",
  "What do you call a bee that can’t make up its mind? A maybe.",
  "Why are frogs so happy? They eat whatever bugs them.",
  "What did the big flower say to the little flower? Hi, bud.",
  "Why did the chicken join a band? It had the drumsticks.",
  "What did the paper say to the pencil? You have a good point.",
  "What kind of shoes do ninjas wear? Sneakers.",
  "Why was the belt arrested? It held up a pair of pants.",
  "What do you call a train carrying bubble gum? A chew-chew train.",
  "What do you call a sleeping pizza? A piZZZa.",
  "Why did the robot go on vacation? It needed to recharge.",
  "What do you call a rabbit with fleas? Bugs Bunny.",
  "Why was the computer cold? It left its Windows open.",
  "What do you call two birds in love? Tweethearts.",
  "What kind of room has no doors or windows? A mushroom.",
  "Why did the moon skip dinner? It was already full.",
  "Why did the marker quit? It felt drawn out.",
  "What did the volcano say to the mountain? I lava you.",
  "What do you call an alligator in a vest? An investigator.",
  "Why did the tortilla chip start dancing? Somebody put on the salsa.",
  "What did the traffic light say to the car? Don’t look, I’m changing.",
  "What kind of music do planets like? Neptunes.",
  "Why did the duck become a detective? It always quacked the case.",
  "What do you call a potato wearing glasses? A spec-tater.",
  "What do you call a sleeping dinosaur? A dino-snore.",
  "What do you call a fancy sea creature? Shell-e-gant.",
  "Why did the student bring a ladder to school? The grades were too high.",
  "Why did the phone wear glasses? It lost its contacts.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "What do you call a tiny mother? A minimum.",
  "Why did the astronaut break up with the moon? It needed space.",
  "Why are fish so smart? They live in schools.",
  "What do you call a cow during an earthquake? A milkshake.",
  "Why did the notebook sit by the window? It wanted a better outlook.",
  "What did the bread say before the race? I’m on a roll.",
  "Why was the keyboard so relaxed? It had plenty of space.",
  "What do you call a dinosaur that crashes its car? Tyrannosaurus wrecks.",
  "What do you call a pig that knows karate? A pork chop.",
  "Why did the socks go to school? They wanted to improve their pairing.",
  "What do you call a sheep with no legs? A cloud.",
  "What do you call a fast vegetable? A runner bean.",
  "Why did the chef become a teacher? He had the recipe for success.",
  "What kind of button can’t unbutton? A belly button.",
  "Why did the chair get promoted? It always supported everyone.",
  "What do you call a musical insect? A hum-bug.",
  "Why did the ruler feel important? It was always measuring up.",
  "What did one volcano say to the other? You rock.",
  "Why did the pencil cross the road? To draw the other side.",
  "What do you call a group of musical whales? An orca-stra.",
  "What do you call a cat that loves bowling? An alley cat.",
  "Why was the geometry class so calm? Everyone knew their angles.",
  "Why did the sandwich go to the gym? It wanted better buns.",
  "What do you call an elephant that doesn’t matter? Irrelephant.",
  "Why did the lamp do well in school? It was very bright.",
  "What do you call a musical mountain? Rock and roll.",
  "Why did the shoe go to school? It wanted to become a smart sneaker.",
  "What do you call a frog’s favorite drink? Croak-a-cola.",
  "Why did the apple stop in the middle of the road? It ran out of cider.",
  "What do you call a happy cowboy? A jolly rancher.",
  "Why did the cookie sit near the computer? It wanted to clear its cache.",
  "What did the ceiling say to the floor? I’ve got you covered.",
  "Why was the dictionary so confident? It had the last word.",
  "What kind of bird works at a construction site? A crane.",
  "Why did the student put a pencil behind the ear? It was a sharp idea.",
  "Why did the tree get a computer? It wanted to log in.",
  "What do you call a musical computer? A Dell-ightful performer.",
  "What do you call a fish that practices medicine? A sturgeon.",
  "Why did the backpack smile? It was packed with good stuff.",
  "What did the calculator say to the student? You can count on me.",
  "Why was the glue so popular? It always stuck with its friends.",
  "What do you call a funny mountain? Hill-arious.",
  "Why did the light bulb get an A? It had a bright answer.",
  "What do you call a sheep that can sing? Lady Baa-Baa.",
  "Why was the science book excited? It had great chemistry.",
  "What do you call a bear in the rain? A drizzly bear.",
  "Why was the pencil case so calm? It had everything under control.",
  "What did the stamp say to the envelope? Stick with me and we’ll go places.",
  "Why did the soccer ball quit the team? It was tired of being kicked around.",
  "What do you call a very small valentine? A valen-tiny.",
  "Why did the music note go to school? It wanted to be sharp.",
  "What did the desk say after a long day? I need to drawer the line.",
  "Why did the banana wear sunscreen? It didn’t want to peel.",
  "What do you call a rabbit who tells jokes? A funny bunny.",
  "Why did the pencil get a trophy? It was on point.",
  "What do you call a fish that loves basketball? A slam-mackerel.",
  "Why did the notebook get invited everywhere? It always had good lines.",
  "What did one battery say to the other? I’m positive we’ll get through this.",
  "Why did the student sit on the clock? To be on time.",
  "What do you call a lazy kangaroo? A pouch potato.",
  "Why did the broom get a good grade? It swept the test.",
  "What do you call a school of musical fish? A bass class.",
  "Why did the eraser get invited to every group project? It was great at fixing mistakes.",
  "What do you call a clever sandwich? A smartwich.",
  "Why did the basketball bring a pencil? It wanted to draw a foul.",
  "What do you call a crab that shares? Shellfish? Nope. Generous.",
  "Why did the student bring string to class? To tie up loose ends.",
  "What do you call a bee that lives at school? A spelling bee.",
  "Why did the notebook wear a jacket? It had a lot of drafts.",
  "What do you call a detective at the beach? Sherlock Foams.",
  "Why did the backpack become class president? It carried everyone.",
  "What do you call a chill dinosaur? A relax-a-saurus.",
  "Why did the marker sit down? It needed a little cap time.",
  "What do you call a sheep that knows karate? A lamb chop.",
  "Why did the student take a ruler to lunch? To measure up the sandwich.",
  "What do you call a dog that can tell time? A watch dog.",
  "Why did the pencil sharpen its jokes? It wanted a better point.",
  "What do you call a funny piece of corn? A-maize-ing.",
  "Why did the classroom plant do well? It kept growing every day.",
  "What do you call a very polite dinosaur? A please-osaurus.",
  "Why did the calendar get promoted? It had a lot of dates.",
  "What did the chalk say to the board? Let’s make a good impression.",
  "Why did the stapler feel confident? It had everything together.",
  "What do you call a fish with no eyes? Fsh.",
  "What do you call a cow that tells jokes? Laughing stock.",
  "Why did the book take a nap? It had a long chapter ahead.",
  "What did one locker say to the other? You crack me up.",
  "Why did the pencil bring a friend? It needed a second point of view.",
  "What do you call a cool vegetable? A rad-ish.",
  "Why did the sandwich do well on the test? It was on a roll.",
  "What do you call a musical snack? A jam session.",
  "Why did the globe feel important? The whole world revolved around it.",
  "What do you call a cat who loves school? A purr-fessor.",
  "Why did the student bring a flashlight to math? The problems looked dark.",
  "What do you call a duck that loves jokes? A wise quacker.",
  "What did the notebook say after class? That was noteworthy.",
  "Why did the clock join the band? It had perfect timing.",
  "What do you call a dinosaur that is good at spelling? A spell-a-saurus.",
  "Why did the chair do well in group work? It always pulled up a seat.",
  "What do you call a bear who loves homework? A study cub.",
  "Why did the pencil case laugh? Someone cracked a sharp joke."
];
